param(
    [string]$Mode = "auto",
    [string]$Target = $PWD,
    [switch]$Yes,
    [string[]]$Source,
    [switch]$SkipHooks
)

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$Py = $null
if (Get-Command py -ErrorAction SilentlyContinue) {
    $Py = "py"
} elseif (Get-Command python -ErrorAction SilentlyContinue) {
    $Py = "python"
}

if ($Py) {
    $args = @("$ScriptDir\bootstrap_portable.py", "--mode", $Mode, "--target", $Target)
    if ($Yes) { $args += "--yes" }
    if ($SkipHooks) { $args += "--skip-hooks" }
    foreach ($s in $Source) {
        $args += @("--source", $s)
    }
    & $Py @args
    exit $LASTEXITCODE
}

# Minimal native fallback for Windows hosts without Python.
$ArchiveRoot = Resolve-Path (Join-Path $ScriptDir "..\..\..\..")
$TargetPath = Resolve-Path $Target
$RepoRoot = $TargetPath
$cursor = $TargetPath
while ($cursor -and -not (Test-Path (Join-Path $cursor ".git"))) {
    $parent = Split-Path -Parent $cursor
    if ($parent -eq $cursor) { break }
    $cursor = $parent
}
if ($cursor -and (Test-Path (Join-Path $cursor ".git"))) {
    $RepoRoot = $cursor
}

$skillSrc = Join-Path $ArchiveRoot ".agents\skills\codex-claude-unison"
$skillDst = Join-Path $RepoRoot ".agents\skills\codex-claude-unison"
$agentsSrc = Join-Path $ArchiveRoot ".codex\agents"
$agentsDst = Join-Path $RepoRoot ".codex\agents"
$hybridDir = Join-Path $RepoRoot ".codex-hybrid"
New-Item -ItemType Directory -Force -Path $skillDst, $agentsDst, $hybridDir | Out-Null
Copy-Item -Recurse -Force $skillSrc $skillDst\..\ | Out-Null
Copy-Item -Recurse -Force $agentsSrc\* $agentsDst | Out-Null

$howToSrc = Join-Path $ArchiveRoot "HOW_TO.md"
$readmeSrc = Join-Path $ArchiveRoot "README.md"
$agentsSrcFile = Join-Path $ArchiveRoot "AGENTS.md"
Copy-Item -Force $howToSrc (Join-Path $RepoRoot "HOW_TO.codex-claude-unison.md")
Copy-Item -Force $readmeSrc (Join-Path $RepoRoot "README.codex-claude-unison.md")
if (-not (Test-Path (Join-Path $RepoRoot "AGENTS.md"))) {
    Copy-Item -Force $agentsSrcFile (Join-Path $RepoRoot "AGENTS.md")
}

$inventory = Get-ChildItem -Path $RepoRoot -Recurse -File -ErrorAction SilentlyContinue |
    Where-Object { $_.Name -match 'prompts|system|memdir|memory|outputStyles|tools|AGENTS|CLAUDE|README|HOW_TO' } |
    Select-Object -First 100 |
    ForEach-Object { "- $($_.FullName)" }
$profile = @(
    "# Codex-Claude Unison profile",
    "",
    "Generated by the Windows fallback hookless bootstrap.",
    "",
    "## Notes",
    "- Hooks are not installed by this no-Python fallback. Install Python and rerun bootstrap_portable.py to enable hooks on platforms where Codex supports them.",
    "- Read this file before planning or editing.",
    "",
    "## Candidate source files",
    $inventory,
    "",
    "## Core contract",
    "- Read before edit.",
    "- Prefer the smallest correct change.",
    "- Verify when possible.",
    "- Report verified, inferred, and unverified results distinctly.",
    "- Ask before destructive or shared-state actions.",
    "- Be curious, owner-like, and disciplined."
) -join "`n"
Set-Content -Path (Join-Path $hybridDir "profile.md") -Value $profile -Encoding UTF8
$state = @{ package_version = '2026-05-09-v3.1'; mode = 'repo'; platform = 'windows'; hooks_enabled = $false; bootstrap = 'powershell-fallback-no-python' } | ConvertTo-Json -Depth 3
Set-Content -Path (Join-Path $hybridDir "bootstrap.state.json") -Value $state -Encoding UTF8
Write-Host "Codex-Claude Unison fallback hookless bootstrap applied to $RepoRoot"
